name: Metrics
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          user: vilmapato
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: header, activity, community, repositories
